### ISSUE TITLE
Predict wrong class

### ISSUE THREAD

**Issue by nicejava** [z-mahmud22/Mask-RCNN_TF2.14.0#1]
Your code very good but predict class wrong 
It always result predicts the first class.

Example we class CLASS_NAMES = ['BG', 'A', 'B', 'C', 'D', 'E', 'F']

your code result predict is class A always Whether using images of other classes

**Comment by z-mahmud22** [comment]
Hi @nicejava, could you please elaborate on what you mean by it predicts wrong class by sharing the results you are getting?

**Comment by nicejava** [comment]
Thank for reply

ok i try train 5 class CLASS_NAMES = ['A', 'B', 'C', 'D', 'E']

    # Number of classes (including background)
    NUM_CLASSES = 1 + 5  # Background + object

And I have image for testing 5 class too like this

01.jpg = class A
02.jpg = class B
03.jpg = class C
04.jpg = class D
05.jpg = class E

So after trained i try testing each image but result display first always is 'A' 
No matter where I use it, the results are the same, which is A

such as i try testing 03.jpg which should have received the answer C, but instead received the answer A


r = model.detect([image], verbose=0)
r = r[0]
result r['class_ids'] is 1 every time testing ( [1 1] : [0.97279286 0.9367134 ] )

**Comment by z-mahmud22** [comment]
You would also need to register these class names and assign `class_id` in your `Dataset` class when training using the [add_class](https://github.com/matterport/Mask_RCNN/blob/3deaec5d902d16e1daf56b62d5971d428dc920bc/mrcnn/utils.py#L262) function [here](https://github.com/matterport/Mask_RCNN/blob/3deaec5d902d16e1daf56b62d5971d428dc920bc/samples/balloon/balloon.py#L90). Without this, the model will not learn the specific classes during training and would produce random results during inference.

Please follow this [tutorial](https://engineering.matterport.com/splash-of-color-instance-segmentation-with-mask-r-cnn-and-tensorflow-7c761e238b46) as it gives you a proper walkthrough on how to train mask-rcnn using [your own dataset](https://github.com/z-mahmud22/Mask-RCNN_TF2.14.0#training-on-your-own-dataset).

**Comment by nicejava** [comment]
I try added class like this, draw mask correct predict shape very good. But label show first always it's incorrect result label

![image](https://github.com/z-mahmud22/Mask-RCNN_TF2.14.0/assets/6760497/0a91c5db-3374-4a53-9fd1-80271edbd36f)

I used mrcnn-prediction.py code for predict

model.detect return 1 always 

.. thanks

**Comment by z-mahmud22** [comment]
It's NOT incorrect class labels that your model is returning. In fact, your model is returning always `1` as the class label. I think you are copying the `BalloonDataset` class which is particularly designed for 1 class. Notice that the [load_mask()](https://github.com/z-mahmud22/Mask-RCNN_TF2.14.0/blob/b01adc30edd9adf65cb9c5ca1c842eac6a7c29f7/samples/balloon/balloon.py#L144) function is always [returning](https://github.com/z-mahmud22/Mask-RCNN_TF2.14.0/blob/b01adc30edd9adf65cb9c5ca1c842eac6a7c29f7/samples/balloon/balloon.py#L168) an array of ones (as class IDs) along with the masks. 

However, in your case,  there are 5 different classes. You'd also need to return particular class indices when returning the masks. You can follow the solution suggested in this [issue](https://github.com/matterport/Mask_RCNN/issues/372#issuecomment-377010489) to fix your problem and retrain the network again. 

Particularly, you would need to pass the list of your `class_ids` when loading image with `add_image()` [here](https://github.com/z-mahmud22/Mask-RCNN_TF2.14.0/blob/b01adc30edd9adf65cb9c5ca1c842eac6a7c29f7/samples/balloon/balloon.py#L137) and update the  `return` from `load_mask()` with this `return mask, info['class_ids']`. 

Additionally, you can follow the [notebook](https://github.com/z-mahmud22/Mask-RCNN_TF2.14.0/blob/main/samples/shapes/train_shapes.ipynb) that illustrates how to train Mask R-CNN on the Shapes dataset which happens to be a multiclass dataset similar to yours. I hope this answers your question.

**Comment by z-mahmud22** [comment]
It's NOT incorrect class labels that your model is returning. In fact, your model is always returning `1` as the class label. I think you are directly copying the `BalloonDataset` class which is particularly designed for 1 class. Notice that the [load_mask()](https://github.com/z-mahmud22/Mask-RCNN_TF2.14.0/blob/b01adc30edd9adf65cb9c5ca1c842eac6a7c29f7/samples/balloon/balloon.py#L144) function is always [returning](https://github.com/z-mahmud22/Mask-RCNN_TF2.14.0/blob/b01adc30edd9adf65cb9c5ca1c842eac6a7c29f7/samples/balloon/balloon.py#L168) an array of ones (as class IDs) along with the masks. 

However, in your case,  there are 5 different classes. You'd also need to return particular class indices when returning the masks. You can follow the solution suggested in this [issue](https://github.com/matterport/Mask_RCNN/issues/372#issuecomment-377010489) to fix your problem and retrain the network again. 

Particularly, you would need to pass the list of your `class_ids` when loading image with `add_image()` [here](https://github.com/z-mahmud22/Mask-RCNN_TF2.14.0/blob/b01adc30edd9adf65cb9c5ca1c842eac6a7c29f7/samples/balloon/balloon.py#L137) and update the  `return` from `load_mask()` with this `return mask, info['class_ids']`. 

Additionally, you can follow the [notebook](https://github.com/z-mahmud22/Mask-RCNN_TF2.14.0/blob/main/samples/shapes/train_shapes.ipynb) that illustrates how to train Mask R-CNN on the Shapes dataset which happens to be a multiclass dataset similar to yours. I hope this answers your question.
