### ISSUE TITLE
Cannot use GPU training

### ISSUE THREAD

**Issue by windvibra** [z-mahmud22/Mask-RCNN_TF2.14.0#10]
![微信图片_20240528141407](https://github.com/z-mahmud22/Mask-RCNN_TF2.14.0/assets/46020860/53fb4eb0-2e94-4559-80d6-72e12fefa6d7)
During training, the utilization rate of gpu is 0 and only cpu is used for training. My gpu is 3060 and cuda version is 11.8

**Comment by z-mahmud22** [comment]
HI @windvibra, sorry for my late response. Can you check if TensorFlow is built using CUDA? You can verify if TF is using GPU via: 
```
import tensorflow as tf
print(tf.test.is_gpu_available()) # Should print True if TF can detect GPU
print("Num GPUs Available: ", len(tf.config.list_physical_devices('GPU'))) # Should print the number of GPUs available
```
Additionally, when you trained the model, did you check if the GPU memory was allocated to the model?

**Comment by z-mahmud22** [comment]
I may have an idea. TensorFlow has stopped GPU support from TF 2.11 on native-Windows platform. More details can be found [here](https://www.tensorflow.org/install/pip#windows-native).

You'd have to either use Linux or WSL 2 on Windows to use this repo and TF with GPU support.
