### ISSUE TITLE
Getting weird predictions.

### ISSUE THREAD

**Issue by Carrrlitoth** [z-mahmud22/Mask-RCNN_TF2.14.0#11]
Hi, me and my friend have been training our custom dataset from scratch and the training is going well but when we're trying to make predictions we get really weird results. What could be wrong?
![Screenshot 2024-06-05 123653](https://github.com/z-mahmud22/Mask-RCNN_TF2.14.0/assets/93775001/0c60da71-047f-4c97-a2ee-da66644a97fc)

**Comment by z-mahmud22** [comment]
Hi, it's difficult to determine what happened from a single predicted image. Nevertheless, I can suggest the following materials:

If you have a multiclass problem, you can follow this [notebook](https://github.com/z-mahmud22/Mask-RCNN_TF2.14.0/blob/main/samples/shapes/train_shapes.ipynb) which trains Mask R-CNN on a multiclass shapes dataset. Additionally, you can review the discussions and solutions suggested in these threads: #1, [#372](https://github.com/matterport/Mask_RCNN/issues/372#issuecomment-377010489). 

If it's a binary problem, follow this [tutorial](https://engineering.matterport.com/splash-of-color-instance-segmentation-with-mask-r-cnn-and-tensorflow-7c761e238b46) and this [example project](https://github.com/z-mahmud22/Mask-RCNN_TF2.14.0/tree/b01adc30edd9adf65cb9c5ca1c842eac6a7c29f7/samples/balloon).

**Comment by zikav1** [comment]
Another intresting thing while training our custom dataset is when we're trying to calculate the mAP score always returns 0.0 which is pretty weird. When we use the coco weights we are able to get a score..

**Comment by userwatch** [comment]
Hello @zikav1 I'm trying to test it for a custom dataset. The results are similar to yours.
