### ISSUE TITLE
GOOGLE COLAB PYTHON VERSION

### ISSUE THREAD

**Issue by userwatch** [z-mahmud22/Mask-RCNN_TF2.14.0#13]
Hello, @z-mahmud22 

I am trying to run colab. But it doesn't happen. Did you run it on colab? What is your python version?

Best wishes,

**Comment by z-mahmud22** [comment]
Hi, yes I ran it on google colab with GPU. I used the current Python version on colab which is: **3.10.12**. 

I'm not sure about what you meant by 'it doesn't happen.' Here's a [guide](https://stackoverflow.com/a/77504039/12317368) that you can follow to use the Mask R-CNN model from this repo on colab.

**Comment by userwatch** [comment]
Hi @z-mahmud22, I was able to run the demo. Thank you very much. Did you train on a custom dataset?

**Comment by userwatch** [comment]
its works for me. Thank you very much.  @z-mahmud22 
 I need to train on a custom data set.
Have you tried it with a custom dataset? What resources did you use?
Thanks a lot again.

**Comment by z-mahmud22** [comment]
Yes, I initially trained the model with a custom dataset on google colab with the default free GPU as I didn't have any GPU or cloud access at that time.
 
Please refer to this [section](https://github.com/z-mahmud22/Mask-RCNN_TF2.14.0?tab=readme-ov-file#training-on-your-own-dataset) to learn about training Mask R-CNN on a custom dataset. You can follow this [project](https://github.com/z-mahmud22/Mask-RCNN_TF2.14.0/tree/main/samples/balloon) for single class problems and this [notebook](https://github.com/z-mahmud22/Mask-RCNN_TF2.14.0/blob/main/samples/shapes/train_shapes.ipynb) for multi-class problems.

**Comment by userwatch** [comment]
I see, thank you very much.
Best wishes,
