### ISSUE TITLE
 train False

### ISSUE THREAD

**Issue by neslihancakmak** [z-mahmud22/Mask-RCNN_TF2.14.0#16]
# Create model in training mode
model = modellib.MaskRCNN(mode="training", config=config,
                          model_dir=MODEL_DIR)
----------------------------------

AttributeError                            Traceback (most recent call last)
[<ipython-input-62-7928c4edfc77>](https://localhost:8080/#) in <cell line: 2>()
      1 # Create model in training mode
----> 2 model = modellib.MaskRCNN(mode="training", config=config,
      3                           model_dir=MODEL_DIR)

19 frames
[/content/gdrive/MyDrive/maskrcnn/maskrcnn/mrcnn/model.py](https://localhost:8080/#) in __init__(self, mode, config, model_dir)
   1842         self.model_dir = model_dir
   1843         self.set_log_dir()
-> 1844         self.keras_model = self.build(mode=mode, config=config)
   1845 
   1846     def build(self, mode, config):

[/content/gdrive/MyDrive/maskrcnn/maskrcnn/mrcnn/model.py](https://localhost:8080/#) in build(self, mode, config)
   2003             # padded. Equally, returned rois and targets are zero padded.
   2004             rois, target_class_ids, target_bbox, target_mask =\
-> 2005                 DetectionTargetLayer(config, name="proposal_targets")([
   2006                     target_rois, input_gt_class_ids, gt_boxes, input_gt_masks])
   2007 

[/usr/local/lib/python3.10/dist-packages/keras/src/engine/base_layer_v1.py](https://localhost:8080/#) in __call__(self, *args, **kwargs)
    836                                 self._compute_dtype_object
    837                             ):
--> 838                                 outputs = call_fn(cast_inputs, *args, **kwargs)
    839 
    840                         except tf.errors.OperatorNotAllowedInGraphError as e:

[/usr/local/lib/python3.10/dist-packages/tensorflow/python/autograph/impl/api.py](https://localhost:8080/#) in wrapper(*args, **kwargs)
    691       except Exception as e:  # pylint:disable=broad-except
    692         if hasattr(e, 'ag_error_metadata'):
--> 693           raise e.ag_error_metadata.to_exception(e)
    694         else:
    695           raise

[/usr/local/lib/python3.10/dist-packages/tensorflow/python/autograph/impl/api.py](https://localhost:8080/#) in wrapper(*args, **kwargs)
    688       try:
    689         with conversion_ctx:
--> 690           return converted_call(f, args, kwargs, options=options)
    691       except Exception as e:  # pylint:disable=broad-except
    692         if hasattr(e, 'ag_error_metadata'):

[/usr/local/lib/python3.10/dist-packages/tensorflow/python/autograph/impl/api.py](https://localhost:8080/#) in converted_call(f, args, kwargs, caller_fn_scope, options)
    437     try:
    438       if kwargs is not None:
--> 439         result = converted_f(*effective_args, **kwargs)
    440       else:
    441         result = converted_f(*effective_args)

[/content/gdrive/MyDrive/maskrcnn/maskrcnn/mrcnn/model.py](https://localhost:8080/#) in tf__call(self, inputs)
     13                 gt_masks = ag__.ld(inputs)[3]
     14                 names = ['rois', 'target_class_ids', 'target_bbox', 'target_mask']
---> 15                 outputs = ag__.converted_call(ag__.ld(utils).batch_slice, ([ag__.ld(proposals), ag__.ld(gt_class_ids), ag__.ld(gt_boxes), ag__.ld(gt_masks)], ag__.autograph_artifact(lambda w, x, y, z: ag__.converted_call(ag__.ld(detection_targets_graph), (ag__.ld(w), ag__.ld(x), ag__.ld(y), ag__.ld(z), ag__.ld(self).config), None, fscope)), ag__...
     16                 try:
     17                     do_return = True

[/usr/local/lib/python3.10/dist-packages/tensorflow/python/autograph/impl/api.py](https://localhost:8080/#) in converted_call(f, args, kwargs, caller_fn_scope, options)
    437     try:
    438       if kwargs is not None:
--> 439         result = converted_f(*effective_args, **kwargs)
    440       else:
    441         result = converted_f(*effective_args)

[/content/gdrive/MyDrive/maskrcnn/maskrcnn/mrcnn/utils.py](https://localhost:8080/#) in tf__batch_slice(inputs, graph_fn, batch_size, names)
     66                 inputs_slice = ag__.Undefined('inputs_slice')
     67                 output_slice = ag__.Undefined('output_slice')
---> 68                 ag__.for_stmt(ag__.converted_call(ag__.ld(range), (ag__.ld(batch_size),), None, fscope), None, loop_body, get_state_2, set_state_2, (), {'iterate_names': 'i'})
     69                 outputs = ag__.converted_call(ag__.ld(list), (ag__.converted_call(ag__.ld(zip), tuple(ag__.ld(outputs)), None, fscope),), None, fscope)
     70 

[/usr/local/lib/python3.10/dist-packages/tensorflow/python/autograph/operators/control_flow.py](https://localhost:8080/#) in for_stmt(iter_, extra_test, body, get_state, set_state, symbol_names, opts)
    447       for_fn = _tf_distributed_iterable_for_stmt
    448 
--> 449   for_fn(iter_, extra_test, body, get_state, set_state, symbol_names, opts)
    450 
    451 

[/usr/local/lib/python3.10/dist-packages/tensorflow/python/autograph/operators/control_flow.py](https://localhost:8080/#) in _py_for_stmt(***failed resolving arguments***)
    498   else:
    499     for target in iter_:
--> 500       body(target)
    501 
    502 

[/usr/local/lib/python3.10/dist-packages/tensorflow/python/autograph/operators/control_flow.py](https://localhost:8080/#) in protected_body(protected_iter)
    464     original_body = body
    465     def protected_body(protected_iter):
--> 466       original_body(protected_iter)
    467       after_iteration()
    468       before_iteration()

[/content/gdrive/MyDrive/maskrcnn/maskrcnn/mrcnn/utils.py](https://localhost:8080/#) in loop_body(itr)
     45                     i = itr
     46                     inputs_slice = [ag__.ld(x)[ag__.ld(i)] for x in ag__.ld(inputs)]
---> 47                     output_slice = ag__.converted_call(ag__.ld(graph_fn), tuple(ag__.ld(inputs_slice)), None, fscope)
     48 
     49                     def get_state_1():

[/usr/local/lib/python3.10/dist-packages/tensorflow/python/autograph/impl/api.py](https://localhost:8080/#) in converted_call(f, args, kwargs, caller_fn_scope, options)
    337   if is_autograph_artifact(f):
    338     logging.log(2, 'Permanently allowed: %s: AutoGraph artifact', f)
--> 339     return _call_unconverted(f, args, kwargs, options)
    340 
    341   # If this is a partial, unwrap it and redo all the checks.

[/usr/local/lib/python3.10/dist-packages/tensorflow/python/autograph/impl/api.py](https://localhost:8080/#) in _call_unconverted(f, args, kwargs, options, update_cache)
    458   if kwargs is not None:
    459     return f(*args, **kwargs)
--> 460   return f(*args)
    461 
    462 

[/content/gdrive/MyDrive/maskrcnn/maskrcnn/mrcnn/model.py](https://localhost:8080/#) in <lambda>(w, x, y, z)
     13                 gt_masks = ag__.ld(inputs)[3]
     14                 names = ['rois', 'target_class_ids', 'target_bbox', 'target_mask']
---> 15                 outputs = ag__.converted_call(ag__.ld(utils).batch_slice, ([ag__.ld(proposals), ag__.ld(gt_class_ids), ag__.ld(gt_boxes), ag__.ld(gt_masks)], ag__.autograph_artifact(lambda w, x, y, z: ag__.converted_call(ag__.ld(detection_targets_graph), (ag__.ld(w), ag__.ld(x), ag__.ld(y), ag__.ld(z), ag__.ld(self).config), None, fscope)), ag__...
     16                 try:
     17                     do_return = True

[/usr/local/lib/python3.10/dist-packages/tensorflow/python/autograph/impl/api.py](https://localhost:8080/#) in converted_call(f, args, kwargs, caller_fn_scope, options)
    439         result = converted_f(*effective_args, **kwargs)
    440       else:
--> 441         result = converted_f(*effective_args)
    442     except Exception as e:
    443       _attach_error_metadata(e, converted_f)

[/content/gdrive/MyDrive/maskrcnn/maskrcnn/mrcnn/model.py](https://localhost:8080/#) in tf__detection_targets_graph(proposals, gt_class_ids, gt_boxes, gt_masks, config)
     61                 roi_gt_boxes = ag__.converted_call(ag__.ld(tf).gather, (ag__.ld(gt_boxes), ag__.ld(roi_gt_box_assignment)), None, fscope)
     62                 roi_gt_class_ids = ag__.converted_call(ag__.ld(tf).gather, (ag__.ld(gt_class_ids), ag__.ld(roi_gt_box_assignment)), None, fscope)
---> 63                 deltas = ag__.converted_call(ag__.ld(utils).box_refinement_graph, (ag__.ld(positive_rois), ag__.ld(roi_gt_boxes)), None, fscope)
     64                 deltas = ag__.ld(deltas)
     65                 deltas /= config.BBOX_STD_DEV

[/usr/local/lib/python3.10/dist-packages/tensorflow/python/autograph/impl/api.py](https://localhost:8080/#) in converted_call(f, args, kwargs, caller_fn_scope, options)
    439         result = converted_f(*effective_args, **kwargs)
    440       else:
--> 441         result = converted_f(*effective_args)
    442     except Exception as e:
    443       _attach_error_metadata(e, converted_f)

[/content/gdrive/MyDrive/maskrcnn/maskrcnn/mrcnn/utils.py](https://localhost:8080/#) in tf__box_refinement_graph(box, gt_box)
     23                 dy = (ag__.ld(gt_center_y) - ag__.ld(center_y)) / ag__.ld(height)
     24                 dx = (ag__.ld(gt_center_x) - ag__.ld(center_x)) / ag__.ld(width)
---> 25                 dh = ag__.converted_call(ag__.ld(tf).log, (ag__.ld(gt_height) / ag__.ld(height),), None, fscope)
     26                 dw = ag__.converted_call(ag__.ld(tf).log, (ag__.ld(gt_width) / ag__.ld(width),), None, fscope)
     27                 result = ag__.converted_call(ag__.ld(tf).stack, ([ag__.ld(dy), ag__.ld(dx), ag__.ld(dh), ag__.ld(dw)],), dict(axis=1), fscope)

AttributeError: in user code:

    File "/content/gdrive/MyDrive/maskrcnn/maskrcnn/mrcnn/model.py", line 691, in call  *
        outputs = utils.batch_slice(
    File "/content/gdrive/MyDrive/maskrcnn/maskrcnn/mrcnn/utils.py", line 829, in batch_slice  *
        output_slice = graph_fn(*inputs_slice)
    File "/content/gdrive/MyDrive/maskrcnn/maskrcnn/mrcnn/model.py", line 600, in detection_targets_graph  *
        deltas = utils.box_refinement_graph(positive_rois, roi_gt_boxes)
    File "/content/gdrive/MyDrive/maskrcnn/maskrcnn/mrcnn/utils.py", line 200, in box_refinement_graph  *
        dh = tf.log(gt_height / height)

    AttributeError: module 'tensorflow' has no attribute 'log'

What is the solution?
Thanks.

**Comment by z-mahmud22** [comment]
Are you using this codebase for Mask R-CNN? Because this repo is updated for TensorFlow 2.x versions and `tf.log` doesn't even exist in the [`utils.py`](https://github.com/z-mahmud22/Mask-RCNN_TF2.14.0/blob/407a6fdebd3202698ea98b6bd075a65c24536c2a/mrcnn/utils.py#L202) script as it was depricated in TF 2.0. 

**Please ensure you are using the code from this repo.** Otherwise you'll need to update `tf.log` with `tf.math.log` in line 200 in your `utils.py` and probably you'll run into other issues as well.
