### ISSUE TITLE
could not broadcast input array from shape (A) into shape (B)

### ISSUE THREAD

**Issue by Ronaldoaleoni** [z-mahmud22/Mask-RCNN_TF2.14.0#18]
I'm facing a problem with the height and width shapes, already searched for a similar problem but can't find any, I'm trying to training images with scale superior to 1024x1024, but in the 5-10 epoch the training always fail and returns: ValueError: could not broadcast input array from shape (1024,1024,2) into shape (1280,768,2). Why is this happening?

this is my configuration:
Configurations:
BACKBONE                       resnet101
BACKBONE_STRIDES               [4, 8, 16, 32, 64]
BATCH_SIZE                     2
BBOX_STD_DEV                   [0.1 0.1 0.2 0.2]
COMPUTE_BACKBONE_SHAPE         None
DETECTION_MAX_INSTANCES        35
DETECTION_MIN_CONFIDENCE       0.7
DETECTION_NMS_THRESHOLD        0.3
FPN_CLASSIF_FC_LAYERS_SIZE     1024
GPU_COUNT                      1
GRADIENT_CLIP_NORM             5.0
IMAGES_PER_GPU                 2
IMAGE_CHANNEL_COUNT            3
IMAGE_MAX_DIM                  1024
IMAGE_META_SIZE                18
IMAGE_MIN_DIM                  1024
IMAGE_MIN_SCALE                0
IMAGE_RESIZE_MODE              square
IMAGE_SHAPE                    [1024 1024    3]
LEARNING_MOMENTUM              0.9
LEARNING_RATE                  0.001
LOSS_WEIGHTS                   {'rpn_class_loss': 1.0, 'rpn_bbox_loss': 1.0, 'mrcnn_class_loss': 1.0, 'mrcnn_bbox_loss': 1.0, 'mrcnn_mask_loss': 1.0}
MASK_POOL_SIZE                 14
MASK_SHAPE                     [28, 28]
MAX_GT_INSTANCES               100
MEAN_PIXEL                     [123.7 116.8 103.9]
MINI_MASK_SHAPE                (56, 56)
NAME                           weathering_cfg
NUM_CLASSES                    6
POOL_SIZE                      7
POST_NMS_ROIS_INFERENCE        1000
POST_NMS_ROIS_TRAINING         2000
PRE_NMS_LIMIT                  6000
ROI_POSITIVE_RATIO             0.33
RPN_ANCHOR_RATIOS              [0.5, 1, 2]
RPN_ANCHOR_SCALES              (32, 64, 128, 256, 512)
RPN_ANCHOR_STRIDE              1
RPN_BBOX_STD_DEV               [0.1 0.1 0.2 0.2]
RPN_NMS_THRESHOLD              0.7
RPN_TRAIN_ANCHORS_PER_IMAGE    256
STEPS_PER_EPOCH                100
TOP_DOWN_PYRAMID_SIZE          256
TRAIN_BN                       False
TRAIN_ROIS_PER_IMAGE           200
USE_MINI_MASK                  False
USE_RPN_ROIS                   True
VALIDATION_STEPS               10
WEIGHT_DECAY                   0.0001

And this is the entire error mensage

ValueError                                Traceback (most recent call last)
Cell In[27], line 19
     15 model.load_weights("C:/Users/Ronaldo/Downloads/Mask-RCNN_TF2.14.0-main/weights/mask_rcnn_coco.h5", by_name=True, exclude=["mrcnn_class_logits", "mrcnn_bbox_fc",  "mrcnn_bbox", "mrcnn_mask"])
     18 # train weights (output layers or 'heads')
---> 19 model.train(train_set, test_set, learning_rate=config.LEARNING_RATE, epochs=100, layers='heads')

File ~\anaconda3\envs\mask-weathering2.3\lib\site-packages\mask_rcnn_tf2-1.0-py3.10.egg\mrcnn\model.py:2371, in MaskRCNN.train(self, train_dataset, val_dataset, learning_rate, epochs, layers, augmentation, custom_callbacks, no_augmentation_sources)
   2368 else:
   2369     workers = multiprocessing.cpu_count()
-> 2371 self.keras_model.fit(
   2372     train_generator,
   2373     initial_epoch=self.epoch,
   2374     epochs=epochs,
   2375     steps_per_epoch=self.config.STEPS_PER_EPOCH,
   2376     callbacks=callbacks,
   2377     validation_data=val_generator,
   2378     validation_steps=self.config.VALIDATION_STEPS,
   2379     max_queue_size=100,
   2380     workers=0,
   2381     use_multiprocessing=False,
   2382 )
   2383 self.epoch = max(self.epoch, epochs)

File ~\anaconda3\envs\mask-weathering2.3\lib\site-packages\keras\src\engine\training_v1.py:856, in Model.fit(self, x, y, batch_size, epochs, verbose, callbacks, validation_split, validation_data, shuffle, class_weight, sample_weight, initial_epoch, steps_per_epoch, validation_steps, validation_freq, max_queue_size, workers, use_multiprocessing, **kwargs)
    853 self._check_call_args("fit")
    855 func = self._select_training_loop(x)
--> 856 return func.fit(
    857     self,
    858     x=x,
    859     y=y,
    860     batch_size=batch_size,
    861     epochs=epochs,
    862     verbose=verbose,
    863     callbacks=callbacks,
    864     validation_split=validation_split,
    865     validation_data=validation_data,
    866     shuffle=shuffle,
    867     class_weight=class_weight,
    868     sample_weight=sample_weight,
    869     initial_epoch=initial_epoch,
    870     steps_per_epoch=steps_per_epoch,
    871     validation_steps=validation_steps,
    872     validation_freq=validation_freq,
    873     max_queue_size=max_queue_size,
    874     workers=workers,
    875     use_multiprocessing=use_multiprocessing,
    876 )

File ~\anaconda3\envs\mask-weathering2.3\lib\site-packages\keras\src\engine\training_generator_v1.py:647, in GeneratorOrSequenceTrainingLoop.fit(self, model, x, y, batch_size, epochs, verbose, callbacks, validation_split, validation_data, shuffle, class_weight, sample_weight, initial_epoch, steps_per_epoch, validation_steps, validation_freq, max_queue_size, workers, use_multiprocessing)
    643 model._validate_or_infer_batch_size(batch_size, steps_per_epoch, x)
    644 training_utils_v1.check_generator_arguments(
    645     y, sample_weight, validation_split=validation_split
    646 )
--> 647 return fit_generator(
    648     model,
    649     x,
    650     steps_per_epoch=steps_per_epoch,
    651     epochs=epochs,
    652     verbose=verbose,
    653     callbacks=callbacks,
    654     validation_data=validation_data,
    655     validation_steps=validation_steps,
    656     validation_freq=validation_freq,
    657     class_weight=class_weight,
    658     max_queue_size=max_queue_size,
    659     workers=workers,
    660     use_multiprocessing=use_multiprocessing,
    661     shuffle=shuffle,
    662     initial_epoch=initial_epoch,
    663     steps_name="steps_per_epoch",
    664 )

File ~\anaconda3\envs\mask-weathering2.3\lib\site-packages\keras\src\engine\training_generator_v1.py:239, in model_iteration(model, data, steps_per_epoch, epochs, verbose, callbacks, validation_data, validation_steps, validation_freq, class_weight, max_queue_size, workers, use_multiprocessing, shuffle, initial_epoch, mode, batch_size, steps_name, **kwargs)
    237 step = 0
    238 while step < target_steps:
--> 239     batch_data = _get_next_batch(generator)
    240     if batch_data is None:
    241         if is_dataset:
    242             # The dataset passed by the user ran out of batches.  Now we
    243             # know the cardinality of the dataset.  If steps_per_epoch
    244             # was specified, then running out of data is unexpected, so
    245             # we stop training and inform the user.

File ~\anaconda3\envs\mask-weathering2.3\lib\site-packages\keras\src\engine\training_generator_v1.py:388, in _get_next_batch(generator)
    386 """Retrieves the next batch of input data."""
    387 try:
--> 388     generator_output = next(generator)
    389 except (StopIteration, tf.errors.OutOfRangeError):
    390     return None

File ~\anaconda3\envs\mask-weathering2.3\lib\site-packages\keras\src\utils\data_utils.py:581, in iter_sequence_infinite(seq)
    572 """Iterates indefinitely over a Sequence.
    573 
    574 Args:
   (...)
    578   Batches of data from the `Sequence`.
    579 """
    580 while True:
--> 581     for item in seq:
    582         yield item

File ~\anaconda3\envs\mask-weathering2.3\lib\site-packages\keras\src\utils\data_utils.py:567, in Sequence.__iter__(self)
    565 def __iter__(self):
    566     """Create a generator that iterate over the Sequence."""
--> 567     for item in (self[i] for i in range(len(self))):
    568         yield item

File ~\anaconda3\envs\mask-weathering2.3\lib\site-packages\keras\src\utils\data_utils.py:567, in <genexpr>(.0)
    565 def __iter__(self):
    566     """Create a generator that iterate over the Sequence."""
--> 567     for item in (self[i] for i in range(len(self))):
    568         yield item

File ~\anaconda3\envs\mask-weathering2.3\lib\site-packages\mask_rcnn_tf2-1.0-py3.10.egg\mrcnn\model.py:1796, in DataGenerator.__getitem__(self, idx)
   1794 batch_gt_class_ids[b, :gt_class_ids.shape[0]] = gt_class_ids
   1795 batch_gt_boxes[b, :gt_boxes.shape[0]] = gt_boxes
-> 1796 batch_gt_masks[b, :, :, :gt_masks.shape[-1]] = gt_masks
   1797 if self.random_rois:
   1798     batch_rpn_rois[b] = rpn_rois

ValueError: could not broadcast input array from shape (1024,1024,2) into shape (1280,768,2)

**Comment by z-mahmud22** [comment]
Are your training images grayscale? If yes, can you try converting them to RGB via: `graytorgb = cv2.cvtColor(gray, cv2. COLOR_GRAY2RGB)` and then train?

**Comment by Ronaldoaleoni** [comment]
> Are your training images grayscale? If yes, can you try converting them to RGB via: `graytorgb = cv2.cvtColor(gray, cv2. COLOR_GRAY2RGB)` and then train?

I manage to solve, the images are in RGB, the real problem was the scale, for some reason not all images were in the same scale, even that is defined in the configurations, when i resize them in other ways and try again the epochs goes on and the training goes alright. But i still don't understand why this occured
