### ISSUE TITLE
Nucleus

### ISSUE THREAD

**Issue by justforleisure** [z-mahmud22/Mask-RCNN_TF2.14.0#3]

**Comment by justforleisure** [comment]
can you give me an example about how to use nucleus.py?

**Comment by z-mahmud22** [comment]
Please refer to this [README](https://github.com/z-mahmud22/Mask-RCNN_TF2.14.0/tree/main/samples/nucleus) file for the instructions regarding the nucleus detection project. Detailed information about the dataset and challenge can be found in [Kaggle's page](https://www.kaggle.com/c/data-science-bowl-2018/overview). 

For starters, you can checkout this [notebook](https://github.com/z-mahmud22/Mask-RCNN_TF2.14.0/blob/main/samples/nucleus/inspect_nucleus_model.ipynb) that uses `nucleus.py` to inspect the trained model.
