### ISSUE TITLE
Error when i try to train the model

### ISSUE THREAD

**Issue by setzin** [z-mahmud22/Mask-RCNN_TF2.14.0#4]
Hello, this error appears to me when i try to train the model:
ValueError: Dimensions must be equal, but are 256 and 28 for '{{node mrcnn_mask_loss/mul}} = Mul[T=DT_FLOAT](mrcnn_mask_loss/GatherV2_1, mrcnn_mask_loss/Log)' with input shapes: [?,256,256], [?,28,28].

**Comment by z-mahmud22** [comment]
Hi @setzin, it seems like you are having a dimension mismatch in your data. Could you check and verify that the dimensions are the same? Also, please share the complete error traceback.
