### ISSUE TITLE
Run with GPU 

### ISSUE THREAD

**Issue by zikav1** [z-mahmud22/Mask-RCNN_TF2.14.0#9]
Hi, thanks for the updated repo of matterports model! I was wondering since you run this on GPU, how did you install CUDA and cuDNN? I've tried many ways of installing it and didnt manage to get it working. Thanks again

**Comment by z-mahmud22** [comment]
Hi, this is actually more specific to your system specs and not quite relevant here. 

However, depending on your OS, you can download and configure the latest CUDA version from [here](https://developer.nvidia.com/cuda-toolkit). I recommend using CUDA [11.8](https://developer.nvidia.com/cuda-11-8-0-download-archive) or [12.1](https://developer.nvidia.com/cuda-12-1-0-download-archive), as they are currently the most stable versions.

**Comment by zikav1** [comment]
Yes I know but didn't know where to ask you. Yes we are using a wsl ubuntu env 20.04 with a nvidia geforce rtx 4090 so I also think that 11.8 should work with TF2.14.0.

**Comment by zikav1** [comment]
Anyways managed to run the model on the GPU, thanks for this repo.

**Comment by nickzheng1** [comment]
> Anyways managed to run the model on the GPU, thanks for this repo.

Dear zikav1,
Did you succeed? Because my computer is similiar to yours but I still encountered a lot of bugs, may I ask what versions you installed on your wsl2?
